### ISSUE TITLE
Better Dragging-Fields Behavior: Solution Found

### ISSUE THREAD

**Issue by katsup-sauce** [dazeysan/SPLU#100]
I think I found something that will work to improve the awful dragging we have now for the player fields.

https://rubaxa.github.io/Sortable/

This Javascript example has handles next to text fields so that you can freely edit the fields and drag the fields. The behavior of the field being dragged is standard/intuitive.

The heading is "Drag handle and selectable text" located about halfway down the page.

**Comment by dazeysan** [comment]
Drag-able sorting now implemented in saved Locations, saved Players, and saved Favorites.
Should replace the old sorting functionality I had originally implemented for the players in the main play view.

**Comment by dazeysan** [comment]
Better dragging behavior was added to the main window for players in 5.8.0
