### ISSUE TITLE
The word "yesterday" has been replaced by the yyyy-mm-dd of the date.

### ISSUE THREAD

**Issue by katsup-sauce** [dazeysan/SPLU#2]
The word "yesterday" has been replaced by the yyyy-mm-dd of the date. Actually, all the phrases (IN THE FUTURE, BEFORE YOU WERE BORN) are gone except for the word "today." I believe the code to make the words show up is still written into SPLU, but it stopped working around 5.0 or 5.1.

**Comment by dazeysan** [comment]
Was the way that SPLUtoday was defined.  It was missing leading 0s in the month and day so it broke the calculation later on.
