### ISSUE TITLE
The "Get Recent" list displays plays in alphabetical order instead of reverse-chronological order.

### ISSUE THREAD

**Issue by katsup-sauce** [dazeysan/SPLU#3]
The "Get Recent" list displays plays in alphabetical order instead of reverse-chronological order. So if you enter your plays in the order you played them that day, you can't tell by looking at the list which game you played first, etc. To see this, you can see that 3/21/2015 lists "Tichu, Tichu, Tichu, Zark City, Zark City," which places the game we played before W&B came over and the game we played after the Tichus together.

**Comment by dazeysan** [comment]
The API returns plays sorted by Date then Alpha.  Need to sort my data by Date then PlayID.

**Comment by dazeysan** [comment]
Sorting is now the same as BGG, Date Descending then Play ID Ascending
