### ISSUE TITLE
Allow users to add Groups (like "Jimmy-kat-Jesse-Joe-Paul") to a Filter (like "Outer Planes").

### ISSUE THREAD

**Issue by katsup-sauce** [dazeysan/SPLU#39]
Right now the only way to see your groups (like WBJK) is to filter on ALL, which for some of us is really long. I want to be able to make a filter called "All My Groups" and add my groups to it. I also want to be able to just add common groups to filters, like putting LPJK into the "Family" filter.

**Comment by dazeysan** [comment]
Backend code is there for groups in the Players filters.  Can manually add something like "group-KJ" to the filter to get the group named "KJ" to show up when that filter is selected.  Need to add GUI for it, will be tough as the Players/Groups tabs are really just showing different columns of a larger "table".

**Comment by dazeysan** [comment]
GUI Added in 5.3.9
