### ISSUE TITLE
Add "Duration" field to filters

### ISSUE THREAD

**Issue by katsup-sauce** [dazeysan/SPLU#42]
Things to take into account with this:

0 - ignore entirely OR just calculate average of the ones that really were entered and treat 0 as though it were the average to allow play-count to remain intact while showing stats on duration

126 - Default interpretation of numbers in the Duration field is in minutes. "126" is seen as 126 minutes.

1:26 - Treat colons that appear in the Duration field as necessitating a conversion from hours:minutes to straight minutes, so 1:26 would have to become 60+26=86.

abc - Ignore Duration fields with alpha characters

Allowing user to use the = searching might be good, especially if they want to find/fix/weed out the plays where they may have entered extraneous data from the time before the field was used for anything standard. (Or to make use of their own code that they're still using.)

Allowing the user to limit on a duration range the way they can with dates would work as long as SPLU did all the 126 vs. 1:26 calculations on the fly and the user was forced to enter what they were searching for as minutes.

**Comment by dazeysan** [comment]
Current Beta has Exactly, Greater Than, Less Than, and Contains filter for Duration Field.
