### ISSUE TITLE
Mass Copy needs to give feedback when done

### ISSUE THREAD

**Issue by katsup-sauce** [dazeysan/SPLU#70]
Ideal: Copied 9/136 plays
then NEEDS to say "Done" when finished.
Current behavior is to keep displaying the last game copied, but this could be just SPLU taking a long time on that one game--user doesn't know.

**Comment by dazeysan** [comment]
Shows "Copying X of Y" under copy button and "Copied X of Y.  Finished" when done.
In theory also says that it "Hit a snag" and provides a link to "Keep Going" if there was an error.
