### ISSUE TITLE
Make columns sortable in Locations / Wins / Beginner's Luck stats

### ISSUE THREAD

**Issue by katsup-sauce** [dazeysan/SPLU#76]
Make columns sortable in Locations / Wins / Beginner's Luck stats. Click once to sort descending (biggest number on top) and again to sort ascending.

**Comment by dazeysan** [comment]
Mostly added to Wins/Locations/Luck stats.  Still need to add sorting by average column.  DynamicSort is giving me trouble with the floats.

**Comment by dazeysan** [comment]
Done for everything except Game Details stat which doesn't do columns the same way as the others.
