### ISSUE TITLE
The 'Type of Game' choice-menu has 'Board' highlighted by default.

### ISSUE THREAD

**Issue by katsup-sauce** [dazeysan/SPLU#84]
The 'Type of Game' choice-menu [board | rpg | video] has 'Board' highlighted by default. It doesn't actually sort on board games, but it looks like it already is. The better behavior would be for none of the 3 to be highlighted but for them to turn yellow under your cursor like the Beginner's Luck list does.

**Comment by dazeysan** [comment]
Removed initial highlighting.
