### ISSUE TITLE
Player Groups don't handle changes to players

### ISSUE THREAD

**Issue by dazeysan** [dazeysan/SPLU#91]
Not sure exact details but a group will end up with "ghost" players like "fred5678" instead the actual "fred1234" in the data and the code breaks when hitting one of them.

**Comment by katsup-sauce** [comment]
This seems to be fixed after testing with Splu Alpha--deleting a player that was added to a group did not freak anything out or throw any errors in the console.

**Comment by dazeysan** [comment]
It had still broken groups when editing a player but should now be fixed.
